### PR TITLE
resolved your problem

### PR DESCRIPTION
**Pull request by easybest**
resolved your problem

### CODE REVIEW

**Comment by kopax** [comment]
> You have a problem with the usage, and you can see this pr: kopax/spring-data-mybatis-testing#2 this pr include @OneToMany , rest projection and extend-xml issues.

If I may resume : 

- extend-xml: I forgot to use @Query("req") annotation
- rest projection: 
- OneToMany: usage of  @JoinColumn(name = "SITE_SERVICE_ID", referencedColumnName = "ID") instead of @JoinTable

How does @OneToMany know the table where to join ?

I've also seen that you used a custom repository : 

      maven { url "https://oss.sonatype.org/content/repositories/snapshots" }

and a custom starter 

    compile("com.ifrabbit:spring-boot-starter-data-mybatis:1.0.8.BUILD-SNAPSHOT")

I was using the jar directly from spring-data-mybatis.

I though with the __spring-data-mybatis__ jar I had convenient access to any snapshot.
Do you recommend me to swap for the starter ?

**Comment by easybest** [comment]
hi,
@OneToMany has two styles: 
 * @JoinColumn : just use a foreign key in the target entity
 * @JoinTable : if you use a join table to connect two entities

@ManyToMany has one style:
 * @JoinTable

**Comment by easybest** [comment]
add   maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
is because 1.0.8 has not been released. 
when use a released-version, it is not need.

**Comment by easybest** [comment]
Highly recommended to use "com.ifrabbit:spring-boot-starter-data-mybatis" if you use spring boot.

**Pull request merged**
